### ISSUE TITLE
Species dropdown list is drawn out of screen

### ISSUE THREAD

**Issue by l29ah** [freeorion/freeorion#1196]
![screenshot](https://dump.bitcheese.net/files/bilaseg/screenshot-freeorion-off-screen-dropdown.png)

**Comment by Vezzra** [comment]
Should be sufficiently addressed by #1183.

**Comment by l29ah** [comment]
No // 29d1da701b3f6967915f178710e43ae9f03ad436 doesn't fix it.

**Comment by Vezzra** [comment]
No change at all, or what exactly is the issue that remains?

**Comment by l29ah** [comment]
Species dropdown list is drawn out of screen.

**Comment by Vezzra** [comment]
So, basically, #1183 didn't change anything at all. Well, in this case we need to reopen.

@LGM-Doyle, any ideas? I assume the fix you provided solved the problem on your system...

**Comment by LGM-Doyle** [comment]
To be clear, when it is working correctly the drop down list has at least one row and no more rows than can fit on the available screen space.  It has a scroll bar and keyboard navigation and selection works.  If there is not room for even one row, then one  row is still drawn and this row will extend offscreen.  

@Vezzra I'm assuming that you have checked OSX and it works for you.

I'm guessing the whatever window manager is being used is not reporting screen size in a way that the app understands.

@l29ah, I'll ask the standard list of questions.
- Are you running a clean build of the latest master?
- Does the change to the SideBar focus drop down work for you?  If you shrink your side panel and drag it to the bottom of the screen does the focus drop down clip itself to the screen edge?
- What OS and version are you using?
- If you are not using windows/OSX, what desktop/window manager are you using?

**Comment by Vezzra** [comment]
@LGM-Doyle, your fix works perfectly fine on OSX.

**Comment by l29ah** [comment]
AFAIK, apps don't ask window managers about their window sizes, but ask X.
Yes, with your patch on top.
No, it's drawn out of screen as well.
Gentoo. What version?
xmonad

**Comment by Vezzra** [comment]
> Yes, with your patch on top.

Latest master has the fix already merged (799eccd51fe22d5bcd43babedc91c047584fa1fe).

> Gentoo. What version?

Well, the version/release of Gentoo you're using. I don't know what the version/release numbering/naming scheme for Gentoo is, but there has to be one. E.g. the Linux system I have on one of my computers here is Kubuntu 16.04.

**Comment by dbenage-cx** [comment]
@Vezzra Gentoo is a rolling release, so does not have version numbers per se

**Comment by LGM-Doyle** [comment]
It was a joke 😆 

I think xmonad is the key piece of information for this bug.

**Comment by Vezzra** [comment]
> It was a joke 😆

Oh, oops. My ignorance got me... 😋

**Comment by l29ah** [comment]
> Latest master has the fix already merged (799eccd).

Ok, i've messed this up a bit. Anyway, reproduces on 9876533a4.

**Comment by LGM-Doyle** [comment]
@Vezzra, I've removed myself from this issue.  I think that the next step is to determine how xmonad different from other X11 systems in reporting either screen/appsize. I don't have xmonad setup.

**Comment by Vezzra** [comment]
I've reassigned this issue to the "optional for 0.4.7" milestone, as it apparently only occurs with very specific setups (xmonad), and unless there is someone with that setup who is willing to try to come up with a fix there isn't much we can do about it anyway, unfortunately.

I can't hold up the release for this.

**Comment by dbenage-cx** [comment]
I tried xmonad 0.13 and could reproduce this issue with 29d1da7, but looks resolved as of current (e187616).
However, xmonad looks highly customizable and I did not look into altering configuration after install/reboot, so the setup may be atypical.

@l29ah Still an issue with your setup?

**Comment by l29ah** [comment]
No, it works okay now, thanks.
