### ISSUE TITLE
Building in progress icon not displaying progress on sidepanel

### ISSUE THREAD

**Issue by MatGB** [freeorion/freeorion#1201]
### Environment

* **FreeOrion Version**: #1192 rebased to master
* **Operating System**: Linux
  * Compiled from source

### Description
I think this is probably a result of the fractional progress merge, but the sidepanel icons that should display building progress aren't showing any at all.

**Comment by geoffthemedio** [comment]
Should be fixed https://github.com/freeorion/freeorion/commit/4f306bf408828add35f3474502935d70f2990f3b

**Comment by MatGB** [comment]
![screenshot_20170115_162657](https://cloud.githubusercontent.com/assets/11533206/21964247/44a5d938-db40-11e6-8e25-0a2ed9a135ae.png)
Still happening for me, I'm playing with #1192 and #1209 rebased to master at d413c55, it's possible there's a clash there if it's needed I can compile a pure master but I'm testing too many features in my actual games.

**Comment by TheSilentOne1** [comment]
I see this as well with a clean build from master.
