### ISSUE TITLE
Availability of freeorion.freeorion-godot

### ISSUE THREAD

**Issue by agrrr3** [freeorion/freeorion#3399]
After initially providing feedback to the shipping of godot in snappy and the freeorion.freeorion-godot command provided by snap, this tracks the availability of the godot client via snap in the master branch

~~@o01eg i tried to run freeorion.freeorion-godot from o01eg/build-godot-fix-deb (f8cf97c64a03c05ebf6b70f1d5868d373615d7cb) built via snapcraft.io..builds (available currently at freeorion --channel latest/edge rev192). This should actually be comment on #3339 (i mixed up my snaps and got confused shortly)

It does start the main freeorion screen in godot if you run it inside of a freeorion directory. I guess directories are set up wrong maybe it needs the default directory there. 
```
$ freeorion_edge.freeorion-godot 
WARNING: cgroup v2 is not fully supported yet, proceeding with partial confinement
Godot Engine v3.2.stable.custom_build - https://godotengine.org
OpenGL ES 3.0 Renderer: Mesa DRI Intel(R) HD Graphics 4400 (HSW GT2)
 
[2021-04-12 19:55:05.284413] [0x00007f910239fa40] [info]    Resources directory /home/agrrr3/default from config.xml missing or does not contain expected files. Resetting to default.
terminate called after throwing an instance of 'boost::filesystem::filesystem_error'
  what():  boost::filesystem::canonical: No such file or directory: "/home/agrrr3/../../default"
```

Starting a game in main screen (after running inside a freeorion directory) does this:
```$ freeorion_edge.freeorion-godot 
WARNING: cgroup v2 is not fully supported yet, proceeding with partial confinement
Godot Engine v3.2.stable.custom_build - https://godotengine.org
OpenGL ES 3.0 Renderer: Mesa DRI Intel(R) HD Graphics 4400 (HSW GT2)
 
Systems from optionsDB 150
execv failed: /snap/freeorion_edge/192/usr/bin/freeoriond: No such file or directory
[xcb] Unknown sequence number while processing queue
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
godot3-runner: ../../src/xcb_io.c:260: poll_for_event: Assertion `!xcb_xlib_threads_sequence_lost' failed.
[xcb] Unknown sequence number while processing queue
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
godot3-runner: ../../src/xcb_io.c:260: poll_for_event: Assertion `!xcb_xlib_threads_sequence_lost' failed.
```
~~

**Comment by o01eg** [comment]
@agrrr3 It is related to https://github.com/freeorion/freeorion/tree/build-godot branch. Is it fixed now?

**Comment by Vezzra** [comment]
@agrrr3, closed as resolved/invalid/...?

**Comment by agrrr3** [comment]
It seems the command is not in master. So not really solved.
