### ISSUE TITLE
Can't manage fleets, sometimes, for certain ships in certain systems

### ISSUE THREAD

**Issue by Oberlus** [freeorion/freeorion#3818]
Bug Report
==========

Environment
-----------

* **FreeOrion Version**:
   f9e776b, Windows 10, Weekly development build.
   f9e776b and 857b988, Ubuntu 20.04, compiled from source.

Description
-----------
Sometimes, some of the ships built at my capital (only planet building ships, so probably not related to what planet) can't be managed in the fleet window:
- merge system ships into fleet does nothing.
- drag&drop some fleets over some other ships do work, but not when certain fleet or ship is involved.

After moving the fleets to another system, fleets and ships can be managed without problem, but the problem can arise again later.

Steps to reproduce
------------------
Load the attached saved game (played in Ubuntu 20.04, FO version 857b988) and try to merge all ships of capital system into a single fleet.

[FO_55_cant_merge_fleets_at_capital.sav.zip](https://github.com/freeorion/freeorion/files/8601939/FO_55_cant_merge_fleets_at_capital.sav.zip)
[FO_55_cant_merge_fleets_at_capital.logs.zip](https://github.com/freeorion/freeorion/files/8601943/FO_55_cant_merge_fleets_at_capital.logs.zip)

**Comment by geoffthemedio** [comment]
Possibly related to https://github.com/freeorion/freeorion/commit/9c2c59254777a2f91368ab63f777988fb4063646

**Comment by Oberlus** [comment]
For the record, all ships (those that could be managed and those that couldn't) had never moved from the shipyard in which they were built.

**Comment by geoffthemedio** [comment]
hopefully fixed by https://github.com/freeorion/freeorion/commit/ab82e9ab6f9c450e057289b58ddd92ff8aabc3ce

**Comment by Oberlus** [comment]
I still have this problem.
In the attached save, version 9783ded, I produced two batches of troop ships, in different turns, and they could be merged in the same turn the second batch was produced. OK.
Then I finished two ships of different ship designs (symbiotic interceptor and symbiotic bomber) in the same turn, 31, and these two fleets of 1 ship each can't be merged in that turn. 

[issue_3818_extra_save_and_logs.zip](https://github.com/freeorion/freeorion/files/8629782/issue_3818_extra_save_and_logs.zip)

**Comment by Oberlus** [comment]
@geoffthemedio did you get a notification of my previous comment? I think this issue is not fully resolved.

**Comment by geoffthemedio** [comment]
yes

**Comment by geoffthemedio** [comment]
probably fixed by 6807519f9faaaf0bd8b89d05f9e17093d78aac2b
