### ISSUE TITLE
Damage Control techs need further balancing

### ISSUE THREAD

**Issue by cpeosphoros** [freeorion/freeorion#540]
Refer to: http://www.freeorion.org/forum/viewtopic.php?f=15&t=10006&view=unread&sid=96ccf93875079e58510e2de75d3978b7#unread

MatGB said:

> this includes both the techs and the auto-repair hulls, ideally no repairs should happen immediately after combat except for Logistics, Nanobot and BioAdaptive, and none of them should be complete. Plus, the techs should repair based on current structure not max structure, forcing heavily damaged big ships to limp home for repairs not simply hide for a couple turns

**Comment by Vezzra** [comment]
@MatGB, do you want to do any work on this front for 0.4.6?

**Comment by MatGB** [comment]
Maybe. It's a low priority compared to other stuff, but if I've time _and_ we get the Drydock stuff agreed/completed then it'd be a good companion to it.

Alternatively, if someone else wants to give it a go holler and I'll be more clear about what I've in mind, it's spread around multiple forum threads at the moment.

**Comment by Vezzra** [comment]
Hm, ok, so I'll leave that as undecided/optional.

**Comment by Vezzra** [comment]
@MatGB: do you consider this issue sufficiently addressed by all the changes/adjustments that went in 0.4.6 to close this issue, or should we keep it open because there is still enough that needs to be done on that front?

**Comment by MatGB** [comment]
This bit

>  the techs should repair based on current structure not max structure, forcing heavily damaged big ships to limp home for repairs not simply hide for a couple turns

still isn't done, need to change fleet field repair and advanced damage control to be %age current structure, easy to code, not so easy to balance or get the AI updated for.

It was a low priority before Release thing, but it can get done now.

**Comment by Vezzra** [comment]
Ok, so it needs to stay open.

**Comment by Vezzra** [comment]
@MatGB: any updates for this one, or does what you said last September still apply?

**Comment by Vezzra** [comment]
@MatGB, status update on this?

**Comment by dbenage-cx** [comment]
I've a [potential branch](https://github.com/freeorion/freeorion/compare/master...dbenage-cx:fix-540_damage_control_tech-current_structure) covering only the techs (as that was the last mention).
If no one else is currently working on it, I can take assignment.

If the scope should still include hulls, will open discussion thread to work out details.

**Comment by Vezzra** [comment]
> If no one else is currently working on it, I can take assignment.

Fine with me - @MatGB? You working on this, or can @dbenage-cx take it up?

**Comment by MatGB** [comment]
Happy for anyone to take it, sorry for delay answering the email got lost in my inbox.  I definitely at some point want the techs to unlock parts that improve them in some way but what's in the linked branch looks fine as a starter, not sure about the 50% cap but will be happy to look at it when I've time

**Comment by dbenage-cx** [comment]
@MatGB I've changed it a bit since you viewed. Advanced Damage Control title no longer fit the effect, so adjusted it to improve on Basic Damage Control and added a new tech as successor to Fleet Field Repair.
