### ISSUE TITLE
Bombardment display UI

### ISSUE THREAD

**Issue by MatGB** [freeorion/freeorion#672]
I'm finally playtesting all the new bombardment weapons to see how valid the strategy is. It's probably going to be a good, solid strategy, but the current UI is terrible and confusing.

Problem 1): If you select a fleet within a system entirely made up of bombard ships of the same weapon fit, you also need to select each individual ship to initiate a bombard. That bombard will last for one turn only then you need to do the whole thing again.

Problem 2): If you have selected and initiated a bombard, go and do something else within the game, then reload the system (mostly, to check you've ordered a repeat bombard), then the planet you had ordered the bombard for _will display population as if the bombard is already complete_, the only way to check if the planet is actually population zero is to cancel the bombard, select a different system, then come back to this system.

There are other, more minor, issues, but these two are the main ones, the top is a micromanagement problem writ large, if your strategy is to denude the galaxy of life you're going to be clicking a lot of ships _every single turn_. The latter is confusing me constantly.

Ideally selecting a fleet allows you to bombard for that entire fleet, but selecting individual ships allows you to choose which goes where as now. I'm not sure how or if we should enable repeat orders but some method of reminding players is essential, a Sitrep needs to be added telling you what your ships have done as well as your opponent.  The population display issue is a major one that needs dealing with, it's especially a problem when you reload from save and check through your fleets before ending turn.

**Comment by ghost** [comment]
A few more glitches I have observed:

If you have two bombard fleets in a system, they can't attack the same planet.

You can't cancel the bombard order if you move the fleet to a different system.

You can't cancel the bombard order once a planet shows 0 population, even if it isn't actually dead.

When you bombard, the next turn the ship(s) show as bombarding, but no action will be taken.  What you have to do is select the ships, order a bombard, then cancel it, then order it again.  Randomly, you may have to reselect all the ships at each step.

If your bombard strength is more than the current population, but less than pop+growth, the planet isn't wiped, but you can't cancel the glitched order due to the last two glitches above.

**Comment by Vezzra** [comment]
Hm, looks like there are some serious issues with the bombard UI. I wonder if we should try to address those for the release, or keep it flagged for post release (as it's now)?

Comments, opinions?

**Comment by MatGB** [comment]
Depends on how much work it'd be. Currently bombardment isn't there as a strategic help, it needs some fairly major balancing and possibly some effects tweaks as well, so having it a bit buggy for this release (given none of them are new bugs) would be fine.

If on the other hand it's a fairly easy fix then it's definitely bugs, and if it is made better to use then the balancing pass needed will be easier post release.

**Comment by geoffthemedio** [comment]
Substantial UI reworking is never going to be an easy fix...

**Comment by Vezzra** [comment]
Then I guess we should keep it flagged for post release.

**Comment by dbenage-cx** [comment]
Some observations:
-  `Cancel Bombard` checks for orders to rescind, but orders are cleared each turn.
-  While [CleanUpBombardStateInfo](https://github.com/freeorion/freeorion/blob/master/server/ServerApp.cpp#L2732) does appear to clear Planet::m_is_about_to_be_bombarded, that change does not persist when SidePanel checks (even if all of the previous ships have been successfully changed).
-  When a `BombardOrder` for a ship is canceled, it calls `Planet::SetIsAboutToBeBombarded(false)`, which does not seem strictly correct as other ships may still be bombarding.

**Comment by l29ah** [comment]
> Currently bombardment isn't there as a strategic help

Nope, i'd say it's a lot faster and cheaper to bomb your way through in the late game compared to the invasion strategy atm, althrough all the clicking required makes this choice a disaster. I guess it would be even more helpful if i employed the invisible fighter way as the bombs ignore the planetary shields afair.

**Comment by l29ah** [comment]
Okay, now it seems like i can't bombard two turns in a row: on the second turn it says it is going to bombard the planet, it is impossible to cancel the order, and on the next turn the planet's population suggests it wasn't.

**Comment by ghost** [comment]
@l29ah That is a known bug.  The workaround is rather counter intuitive:
Individually select (highlight) all of the bombarding ships in the lower fleet window, then click the bombard button on the planet *three* times.  If you are bombarding multiple planets in a system, you have to repeat it for each planet every turn.  Note that this doesn't work if a planet shows as dead, but isn't, since you don't get a bombard button.
If you don't select anything during your turn, you can sometimes keep the fleet selection across multiple turns, but it makes bombarding multiple systems painful, or any kind of fleet management, for that matter.

**Comment by Oberlus** [comment]
This issue is actually relevant and should be solved.
It hinders the use of bombardment quite a bit, to the point that experienced players ignore this tech branch completely and new players don't realise how to use it (because of the UI bug).
Some veteran players (like @l29ah) have suggested disabling this tech branch.

It would be great if someone with enough knowledge of the code base could look into it. @geoffthemedio? Maybe @TheSilentOne1?

**Comment by TheSilentOne1** [comment]
I would give it a try, but unfortunately not in the next couple of months.

**Comment by agrrr3** [comment]
Ok this problem still persists. I had a look and I am not sure how to progress.
One problem in implementation is a potential mix between ship state and orders. 

If I am not mistaken, the server state only gets influenced by Orders, so if the server is responsible for auto-bombarding the next turn, there are no orders and we would need a StopBombardOrder or similar to tell the server to stop. But then we also have those edge cases like CancelColonizeInvadeBombardScrapShipOrders and I am not sure, if StopBombardOrders should also get cancelled. Basically adding  another type of order is not going to reduce complexity here.

So... one idea would be to have the client to be responsible for auto-bombarding, sending each turn bombardment orders. The good: This would reduce complexity.
The bad: i am not sure how auto-turn works. but if that is server-side only the whole idea is impossible
The ugly: i dont know  where to put such code - either sending missing orders when ready, or rather re-sending the orders when turn update comes in;
also ugly: network communication for resending those orders

another idea i am not sure is feasable: resend the orders in FOCS effects right after decreasing population;
[s]i think we have something for giving move orders, so this could be similar[/s] no we do not have such a thing yet.
