### ISSUE TITLE
AI fails when taking over human empire

### ISSUE THREAD

**Issue by Voker57** [freeorion/freeorion#781]
How to reproduce: load this save http://dump.bitcheese.net/files/bonazal/save-20160723_204151.mps in multiplayer, select "Voker57" and "L29Ah" as human players, other 4 empires set as AI

on ending turn, there's an AI error in log and AI who drives nj's empire disconnects.

**Comment by geoffthemedio** [comment]
It appears that the AI script is attempting to retrieve the AI state information, but this is missing because that empire was previously played by a human.

In the AI log file:

```
2016-07-23 20:40:02.375447 [error] AI : Traceback (most recent call last):
2016-07-23 20:40:02.375447 [error] AI :   File "C:/Users\Geoff\Desktop\FreeOrion_VS2013_SDK\FreeOrionTemp\default\python\AI\FreeOrionAI.py", line 118, in resumeLoadedGame
2016-07-23 20:40:02.376448 [error] AI :     foAIstate = pickle.loads(saved_state_string)
2016-07-23 20:40:02.376448 [error] AI :   File "C:\Users\Geoff\Desktop\FreeOrion_VS2013_SDK\FreeOrionTemp\python27.zip\pickle.py", line 1382, in loads
2016-07-23 20:40:02.376448 [error] AI :     return Unpickler(file).load()
2016-07-23 20:40:02.376448 [error] AI :   File "C:\Users\Geoff\Desktop\FreeOrion_VS2013_SDK\FreeOrionTemp\python27.zip\pickle.py", line 858, in load
2016-07-23 20:40:02.376448 [error] AI :     dispatch[key](self)
2016-07-23 20:40:02.376448 [error] AI :   File "C:\Users\Geoff\Desktop\FreeOrion_VS2013_SDK\FreeOrionTemp\python27.zip\pickle.py", line 880, in load_eof
2016-07-23 20:40:02.376448 [error] AI :     raise EOFError
2016-07-23 20:40:02.376448 [error] AI : EOFError
```

It then seems to play the turn, but has another error when trying to prepare save state info for the next turn...

```
2016-07-23 20:40:07.393143 [debug] AI : Chat Message to human: AI_Error: AI script error in "prepareForSave": "Can't pickle <type 'Boost.Python.enum'>: it's not found as Boost.Python.enum"
2016-07-23 20:40:07.394144 [error] AI : Traceback (most recent call last):
2016-07-23 20:40:07.394144 [error] AI :   File "C:/Users\Geoff\Desktop\FreeOrion_VS2013_SDK\FreeOrionTemp\default\python\AI\freeorion_tools\_freeorion_tools.py", line 95, in wrapper
2016-07-23 20:40:07.394144 [error] AI :     return function(*args, **kw)
2016-07-23 20:40:07.394144 [error] AI :   File "C:/Users\Geoff\Desktop\FreeOrion_VS2013_SDK\FreeOrionTemp\default\python\AI\FreeOrionAI.py", line 144, in prepareForSave
2016-07-23 20:40:07.394144 [error] AI :     dump_string = pickle.dumps(foAIstate)
2016-07-23 20:40:07.394144 [error] AI :   File "C:\Users\Geoff\Desktop\FreeOrion_VS2013_SDK\FreeOrionTemp\python27.zip\pickle.py", line 1374, in dumps
2016-07-23 20:40:07.395144 [error] AI :   File "C:\Users\Geoff\Desktop\FreeOrion_VS2013_SDK\FreeOrionTemp\python27.zip\pickle.py", line 224, in dump
2016-07-23 20:40:07.395144 [error] AI :   File "C:\Users\Geoff\Desktop\FreeOrion_VS2013_SDK\FreeOrionTemp\python27.zip\pickle.py", line 331, in save
2016-07-23 20:40:07.395144 [error] AI :   File "C:\Users\Geoff\Desktop\FreeOrion_VS2013_SDK\FreeOrionTemp\python27.zip\pickle.py", line 419, in save_reduce
2016-07-23 20:40:07.395144 [error] AI :   File "C:\Users\Geoff\Desktop\FreeOrion_VS2013_SDK\FreeOrionTemp\python27.zip\pickle.py", line 286, in save
2016-07-23 20:40:07.395144 [error] AI :   File "C:\Users\Geoff\Desktop\FreeOrion_VS2013_SDK\FreeOrionTemp\python27.zip\pickle.py", line 649, in save_dict
2016-07-23 20:40:07.395144 [error] AI :   File "C:\Users\Geoff\Desktop\FreeOrion_VS2013_SDK\FreeOrionTemp\python27.zip\pickle.py", line 663, in _batch_setitems
2016-07-23 20:40:07.396145 [error] AI :   File "C:\Users\Geoff\Desktop\FreeOrion_VS2013_SDK\FreeOrionTemp\python27.zip\pickle.py", line 331, in save
2016-07-23 20:40:07.396145 [error] AI :   File "C:\Users\Geoff\Desktop\FreeOrion_VS2013_SDK\FreeOrionTemp\python27.zip\pickle.py", line 401, in save_reduce
2016-07-23 20:40:07.396145 [error] AI :   File "C:\Users\Geoff\Desktop\FreeOrion_VS2013_SDK\FreeOrionTemp\python27.zip\pickle.py", line 286, in save
2016-07-23 20:40:07.396145 [error] AI :   File "C:\Users\Geoff\Desktop\FreeOrion_VS2013_SDK\FreeOrionTemp\python27.zip\pickle.py", line 562, in save_tuple
2016-07-23 20:40:07.396145 [error] AI :   File "C:\Users\Geoff\Desktop\FreeOrion_VS2013_SDK\FreeOrionTemp\python27.zip\pickle.py", line 286, in save
2016-07-23 20:40:07.396145 [error] AI :   File "C:\Users\Geoff\Desktop\FreeOrion_VS2013_SDK\FreeOrionTemp\python27.zip\pickle.py", line 748, in save_global
2016-07-23 20:40:07.396145 [error] AI : pickle.PicklingError: Can't pickle <type 'Boost.Python.enum'>: it's not found as Boost.Python.enum
```

**Comment by geoffthemedio** [comment]
Appears to be similar to http://www.freeorion.org/forum/viewtopic.php?p=64093#p64093

**Comment by Vezzra** [comment]
Is an AI taking over for a human player even intended to work? If there is no support for that in the code, this is actually a wontfix, or should be turned into a feature request - right?

**Comment by geoffthemedio** [comment]
It probably should work...  At least in this case it seems to be a bug-like issue preventing it from working.

**Comment by Vezzra** [comment]
Ok, more of an edge case, but still a bug then. Will tag it for release for now.

**Comment by Cjkjvfnby** [comment]
I will look into it at this week.

**Comment by Cjkjvfnby** [comment]
I cannot reproduce this issue, because link to save file is broken for me.

I pushed commit that will fix loading game with empty savestring.

**Comment by geoffthemedio** [comment]
Can or can't reproduce?

Following the link doesn't work, but I can right click and save as successfully.

**Comment by Cjkjvfnby** [comment]
@geoffthemedio, thank you, I have downloaded save file.

**Comment by Cjkjvfnby** [comment]
Fixed in f3f5aaa

**Comment by Voker57** [comment]
This save http://dump.bitcheese.net/files/dypamod/l29ah_v_querens-nj.mps still fails. AI says something empireID being not a member of NULL, then on next turn server segfaults: 

```
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7705330 in Empire::Eliminated() const ()
   from /opt/freeorion/lib/freeorion/libfreeorioncommon.so
(gdb) bt
#0  0x00007ffff7705330 in Empire::Eliminated() const ()
   from /opt/freeorion/lib/freeorion/libfreeorioncommon.so
#1  0x00000000004b18aa in ServerFSM::HandleNonLobbyDisconnection(Disconnection const&) ()
#2  0x00000000004b8214 in boost::statechart::simple_state<WaitingForTurnEnd, PlayingGame, WaitingForTurnEndIdle, (boost::statechart::history_mode)0>::react_impl(boost::statechart::event_base const&, void const*) ()
#3  0x000000000049bfa8 in boost::statechart::state_machine<ServerFSM, Idle, std::allocator<void>, boost::statechart::null_exception_translator>::process_event(boost::statechart::event_base const&) ()
#4  0x00000000004844ff in ServerApp::PlayerDisconnected(boost::shared_ptr<PlayerConnection>)
    ()
#5  0x000000000048d613 in boost::detail::function::void_function_obj_invoker1<boost::_bi::bind_t<void, boost::_mfi::mf1<void, ServerApp, boost::shared_ptr<PlayerConnection> >, boost::_bi::list2<boost::_bi::value<ServerApp*>, boost::arg<1> > >, void, boost::shared_ptr<PlayerConnection> >::invoke(boost::detail::function::function_buffer&, boost::shared_ptr<PlayerConnection>) ()
#6  0x00000000004e19ad in boost::function1<void, boost::shared_ptr<PlayerConnection> >::operator()(boost::shared_ptr<PlayerConnection>) const ()
#7  0x00000000004d96da in ServerNetworking::DisconnectImpl(boost::shared_ptr<PlayerConnection>) ()
#8  0x00000000004dd3a3 in boost::detail::function::void_function_obj_invoker1<boost::_bi::bind_t<void, boost::_mfi::mf1<void, ServerNetworking, boost::shared_ptr<PlayerConnection> >, boost::_bi::list2<boost::_bi::value<ServerNetworking*>, boost::arg<1> > >, void, boost::shared_ptr<PlayerConnection> >::invoke(boost::detail::function::function_buffer&, boost::shared_ptr<PlayerConnection>) ()
#9  0x00000000004e19ad in boost::function1<void, boost::shared_ptr<PlayerConnection> >::operator()(boost::shared_ptr<PlayerConnection>) const ()
#10 0x00000000004e1a6a in boost::detail::function::void_function_obj_invoker0<boost::_bi::bind_t<boost::_bi::unspecified, boost::function<void (boost::shared_ptr<PlayerConnection>)>, boost::_bi::list1<boost::_bi::value<boost::shared_ptr<PlayerConnection> > > >, void>::invoke(boost::detail::function::function_buffer&) ()
#11 0x00000000004d85e8 in ServerNetworking::HandleNextEvent() ()
#12 0x0000000000470b92 in ServerApp::Run() ()
#13 0x0000000000436335 in main ()
```

How to reproduce: load, add human players for Entente, Zaloopa's something, L29Ah, AI for the rest.

**Comment by Cjkjvfnby** [comment]
Looks like we have new issue.

**Comment by geoffthemedio** [comment]
Crash is probably due to this line

https://github.com/freeorion/freeorion/blob/master/server/ServerFSM.cpp#L225

which seems to assume that GetEmpire will return a valid empire pointer, but should check that before dereferencing it.

**Comment by Vezzra** [comment]
Shouldn't [line 227](https://github.com/freeorion/freeorion/blob/master/server/ServerFSM.cpp#L227) take care of that? IIRC if `empire` evaluates to `false` (which, if `GetEmpire` returned a NULL pointer, it should), further evaluation should be cancelled and therefore `!empire->Eliminated()` not getting executed at all - right?

**Comment by geoffthemedio** [comment]
Yes; that's why I added it yesterday.

https://github.com/freeorion/freeorion/blame/master/server/ServerFSM.cpp#L227

**Comment by Vezzra** [comment]
Oh, sorry, didn't realize you already committed a fix. So I guess you're now waiting for a confirmation by @Voker57 that the fix works?

**Comment by geoffthemedio** [comment]
That's a fix for the crash, but there might still be a problem with the AI taking over a human...

**Comment by geoffthemedio** [comment]
Can someone confirm whether it works after the above changes?

I don't want to hold up the release over an "edge case"...

**Comment by Vezzra** [comment]
Can't test right now with multiple human players, but one human player and all others AI should work too. However, doing that apparently causes the human client to terminate shortly after load completes. On my one try I couldn't even do something, the map appeared, and  few seconds later I got the message that connection to the server had been lost and I found myself on the main menu.

Log files: [logfiles.zip](https://github.com/freeorion/freeorion/files/444409/logfiles.zip)

However, these issues could be due to trying to load a save game from an old version. According to the header info, we're dealing with a save created with a version from Aug 21st, and there have been a lot of commits since then.

So, in order to test if the fix works you guys probably need to try to reproduce the issue with a new game based on current master.

**Comment by Vezzra** [comment]
> I don't want to hold up the release over an "edge case"...

I'll leave the "Release v0.4.6" milestone for now, to indicate this issue has some priority, but I won't hold up the release for this. As you said, it seems to be an edge case.

**Comment by Vezzra** [comment]
Just ran a quick test. Started a multiplayer game with only one human and 4 AIs, did a few turns, then quit, reloaded and continued taking over one of the AI empires and let an AI take over mine. Did some more turns, quit, reloaded and took over another AI. Seems to work fine, the only error message I get is an AI script error "Fail to load aiState from saved game", which is to be expected.

**Comment by geoffthemedio** [comment]
From the logs you posted, there's a problem with AI 8 (in AI_7.log):

```
2016-08-30 10:41:13.616125 [debug] AI : Chat Message to human: AI_Error: AI script error in "resumeLoadedGame": "'NoneType' object has no attribute 'empireID'"
2016-08-30 10:41:13.619307 [error] AI : Traceback (most recent call last):
2016-08-30 10:41:13.619362 [error] AI :   File "/Users/user/SoftwareProjekte/FO/src/Xcode/build/Test/FreeOrion.app/Contents/Resources/default/python/AI/freeorion_tools/_freeorion_tools.py", line 95, in wrapper
2016-08-30 10:41:13.619635 [error] AI :     return function(*args, **kw)
2016-08-30 10:41:13.619701 [error] AI :   File "/Users/user/SoftwareProjekte/FO/src/Xcode/build/Test/FreeOrion.app/Contents/Resources/default/python/AI/FreeOrionAI.py", line 121, in resumeLoadedGame
2016-08-30 10:41:13.619819 [error] AI :     foAIstate = AIstate.AIstate(fo.aggression.aggressive)
2016-08-30 10:41:13.619863 [error] AI :   File "/Users/user/SoftwareProjekte/FO/src/Xcode/build/Test/FreeOrion.app/Contents/Resources/default/python/AI/AIstate.py", line 72, in __init__
2016-08-30 10:41:13.620091 [error] AI :     self.empireID = empire.empireID
2016-08-30 10:41:13.620159 [error] AI : AttributeError: 'NoneType' object has no attribute 'empireID'
```

Looks like that AI doesn't have an empire. Did you add too many AIs for the number of empires in the game, or neglect to assign an empire to the last one?

Edit: a bit of testing indicates that doing as I suggest produces the same error.

Adding some safety checks helps, but it's assumed in various places that empireID will always be valid, even for other empires I think, so a variety of places need such checks...

```
        # initialize home system knowledge
        empire = fo.getEmpire()
        if empire is None:
            self.empireID = -1
            print "Unable to get empire object; can't initialize AI"
            return

        universe = fo.getUniverse()
        if universe is None:
            print "Unable to get universe object; can't initialize AI"
            return
```

Probably the client and server should also not allow games to start with a no-empire AI player, but being safer int he Python code would also be good.

**Comment by Vezzra** [comment]
After looking again into this, I noticed something else in the logs, the following lines are in freeoriond.log:

```
...
2016-08-30 13:22:05.895452 [error] Server : ServerApp.cpp:964 : ServerApp::LoadMPGameInit couldn't find save game data for human player with assigned empire id: 9
...
2016-08-30 13:22:05.895641 [error] Server : ServerApp.cpp:1034 : ServerApp::LoadGameInit has 8 established players but 7 entries in player save game data.  Could be ok... so not aborting, but might crash
...
2016-08-30 13:22:07.042287 [error] Server : ServerApp.cpp:1339 : ServerApp::GetPlayerInfoMap: couldn't find an empire for player with id 5
...
2016-08-30 13:22:11.063749 [error] Server : ServerApp.cpp:388 : ServerApp::HandleMessage : Received an message with a sender ID (-1) that differs from the sending player connection ID: 5.  Ignoring.
...
```

I then checked the header info of the savegame, and indeed there is one AI player entry missing in the `player_save_header_data` section. There is no entry for "AI_4", however, in the `empire_save_game_data` section the "Center" empire (empire id 9) is associated with player "AI_4".

I suspect this savegame file got somehow corrupted, and upon reload something goes wrong during the process of establishing player-empire assignments.

**Comment by Vezzra** [comment]
Addendum: Looks like it's not something that goes wrong when loading, but that went wrong when saving. Hence, unless we are able to reliably reproduce a broken savegame like the one we're working with here, I guess there's not much we can do about it...?

**Comment by geoffthemedio** [comment]
Maybe it was broken by loading the game with too many AIs, or an AI without an empire assigned, then saving that game, then trying to reload it again?

**Comment by Vezzra** [comment]
Could be (although, if, then not by me, I examined the original, unaltered savegame file I downloaded via the link provided above). @Voker57?

Nevertheless, even _if_ someone does something like this, it would still be a bug as the code should prevent savegame corruption in these cases. Easiest and most obvious solution: You should not be able to start/continue a game in the multiplayer lobby at all as long as there isn't a exact match between players and empires (no empires without players and no players without empires).

**Comment by Vezzra** [comment]
I'm not sure how to proceed with this issue - the original problem seems to have been addressed, and the theoretical issue we discussed at last is, well, theory. I'm inclined to close this, and open a new issue if something like that turns up again in the future.

Comments, opinions? @Voker57, @geoffthemedio, @Cjkjvfnby?

**Comment by l29ah** [comment]
On Fri, Sep 23, 2016 at 03:39:06AM -0700, Vezzra wrote:

> I'm not sure how to proceed with this issue - the original problem seems to have been addressed, and the theoretical issue we discussed at last is, well, theory. I'm inclined to close this, and open a new issue if something like that turns up again in the future.
> 
> Comments, opinions? @Voker57, @geoffthemedio, @Cjkjvfnby?

It seems working fine now. We had some occasions of a player going out and an AI playing for his empire at a quite good level.

## 

()  ascii ribbon campaign - against html mail
/\  http://arc.pasp.de/   - against proprietary attachments

**Comment by Vezzra** [comment]
Ok, I'm closing this. If the issue turns up again, please open a new issue.
